# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hiramwamae/hiram-yolo-backend:v1.0.2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP


#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: backend-deployment
#  labels:
#    app: backend
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: backend
#  template:
#    metadata:
#      labels:
#        app: backend
#    spec:
#      containers:
#        - name: backend
#          image: brianbwire/brian-yolo-backend:v1.0.0
#          command: ["npm", "start"] 
#          ports:
#            - containerPort: 5000
#          resources:
#            limits:
#              memory: "256Mi"
#              cpu: "500m"
#            requests:
#              memory: "128Mi"
#              cpu: "250m"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: backend-service
#spec:
#  type: LoadBalancer
#  selector:
#    app: backend
#  ports:
#    - protocol: TCP
#      port: 5000
#      targetPort: 5000
#      nodePort: 30100
  