# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hiramwamae/hiram-yolo-client:v1.0.8
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config  # Reference to the ConfigMap
              key: BACKEND_API_URL   # Key within the ConfigMap

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 #update from previous 3000 since am now using port 80 for NGINX
      targetPort: 80
  type: LoadBalancer