---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true

  vars:
    repo_url: "https://github.com/hiramwamae/yolo.git"  # Git clone URL
    project_dir: "/home/vagrant/yolo"  # Project directory in VM

  tasks:
    - name: Remove older Docker packages
      apt:
        name:
          - docker
          - docker.io
          - docker-ce
          - docker-ce-cli
        state: absent
        purge: yes
      ignore_errors: yes
    
    - name: Clean and update apt cache
      apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes

    - name: Install prerequisites for Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install necessary packages
      apt:
        name: 
          - git
          - docker-compose  # Consider manual installation if you need a newer version
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Clone Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: master
        force: yes

  #  - name: Build and start containers with Docker Compose
  #    command: sudo docker compose up -d --build  # Use docker-compose (with hyphen) if installed via apt
  #    args:
  #      chdir: "{{ project_dir }}"

  #  - name: Verify that containers are running
  #    command: docker ps


  roles: 
    - network-setup
    - setup-mongodb  
    - backend-deployment
    - frontend-deployment
    