---
- name: Ansible playbook to dockerize and run yolo e-commerce app using ansible
  hosts: all
  become: true

  vars:
    repo_url: "https://github.com/hiramwamae/yolo.git"  #Git clone URL
    project_dir: "/home/vagrant/yolo"  # Project Directory in VM

  tasks:
    - name: Install necessary packages
      apt:
        name: 
          - git
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Clone Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: master  # Change to the master branch git
        force: yes
  #roles: 
  #  - frontend-deployment
  #  - setup-mongodb   
  #  - backend-deployment
    