---
- name: Pull frontend image from Docker Hub
  community.docker.docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: Create frontend container
  community.docker.docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    tty: true
    published_ports: "{{ frontend_ports }}"
    networks:
      - name: "{{ frontend_network }}"
    restart_policy: always  
    command: "npm start"    
  become: yes

- name: Wait for frontend service to be up
  wait_for:
    port: 3000
    delay: 10  # Wait for 10 seconds before checking
    timeout: 30  # Maximum time to wait for the port to be available








