---
- name: Run MongoDB container
  community.docker.docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    published_ports: "{{ mongo_ports }}"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ mongo_network }}"
    command: "{{ mongo_command }}"
  become: yes

