---
# roles/mongo/tasks/main.yml

- name: Run MongoDB container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    published_ports: "{{ mongo_ports }}"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ mongo_network }}"



#- name: Run MongoDB Container
#  docker_container:
#    name: app-mongo
#    image: mongo
#    ports:
#      - '27017:27017'
#    volumes:
#      - ./app-mongo-data:/data/db
#    networks:
#      - name: app-net
#  tags:
#    - database
#    - backend