---
- name: Pull backend image from Docker Hub
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Create backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    networks:
      - name: "{{ backend_network }}"
    published_ports: "{{ backend_ports }}"
    restart_policy: always
    command: "npm start"  
  become: yes


