---
- name: Pull image from repository
  docker_image:
    name: hiramwamae/hiram-yolo-backend:v1.0.2 
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: hiram-yolo-backend
    image: hiramwamae/brian-yolo-backend:v1.0.2  
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes